Repository Codeit-FESI-06-Team2/MoYeoBang, pull requests merged in 2025-02, with the labels that each got.

#104 FESI-63: 마이페이지 메인 배경화면을 api로 설정
  src/app/mypage/page.tsx
  src/axios/mypage/api.ts
  src/components/mypage/myGathering.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/data/mockUser.ts
  src/hooks/useUserProfile.ts
  src/hooks/userUserGatherings.ts
  src/types/mypage.types.ts
Labels: Feat

#107 Fesi1 83 [fix] : logout 시 토큰 삭제 수정
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/axios/auth.ts
  src/axios/interceptors.ts
  src/components/@shared/Header.tsx
Labels: Fix

#108 FESI-82: 검색 레이아웃 구현 및 api 연동
  src/app/search/page.tsx
  src/axios/search/api.ts
  src/hooks/useSearchGathering.ts
  src/types/gathering.types.ts
Labels: Feat

#110 FESI1-88: hotfix/invalid url
  .github/workflows/build-test.yml
  package-lock.json
  package.json
  public/images/theme_default.png
  src/app/error.tsx
  src/app/gathering/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/axios/gather/apis.ts
  src/components/@shared/EmptyElement.tsx
  src/components/@shared/QueryProvider.tsx
  src/components/@shared/dropdown/DateDropdown.tsx
  src/components/@shared/dropdown/Dropdown.tsx
  src/components/@shared/dropdown/LevelDropdown.tsx
  src/components/@shared/dropdown/LocationDropdown.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
  src/components/@shared/dropdown/SortDropdown.tsx
  src/components/@shared/skeleton/SkeletonCard.tsx
  src/components/@shared/skeleton/SkeletonCardList.tsx
  src/components/@shared/skeleton/SkeletonSlot.tsx
  src/components/@shared/skeleton/SkeletonSlotList.tsx
  src/components/allReview/ReviewFilters.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/selector/GatheringFilters.tsx
  src/components/home/NearDeadlines.tsx
  src/components/home/NearFullCapacities.tsx
  src/hooks/useCalendar.ts
  src/utils/apiCall.ts
Labels: !HOTFIX

#112 FESI1-87: 모임 찾기 목록 무한스크롤 구현
  src/axios/gather/apis.ts
  src/components/gathering/GatheringList.tsx
  src/hooks/useInfiniteScroll.ts
  src/utils/apiCall.ts
Labels: Feat

#113 FESI1-89: 모든 리뷰 무한스크롤 구현 및 lighthouse 1차 개선
  package-lock.json
  package.json
  src/axios/allReview/apis.ts
  src/components/@shared/HeaderTitle.tsx
  src/components/@shared/rating/Rating.tsx
  src/components/allReview/AllReviewList.tsx
  src/components/allReview/RatingSection.tsx
  src/components/allReview/ReviewCard.tsx
  src/components/allReview/ReviewEditDropdown.tsx
Labels: Feat, Refactor, Chore

#115 FESI1-91: 모임 상세 페이지, 유저 페이지 구현
  package-lock.json
  public/icons/Share.svg
  public/icons/gathering_button.svg
  public/icons/gathering_chevron.svg
  public/icons/human.svg
  src/app/gathering/[id]/page.tsx
  src/axios/gather/apis.ts
  src/components/@shared/button/Button.tsx
  src/components/@shared/dropdown/Dropdown.tsx
  src/components/gatheringDetail/GatheringMainSection.tsx
  src/components/gatheringDetail/GatheringReviewSection.tsx
  src/components/gatheringDetail/JoinBoxSection.tsx
  src/hooks/queries/useGathering.ts
Labels: Feat

#116 FESI-63 : 마이페이지 내가 만든 모임 수정, 삭제, 리뷰 작성, 리뷰 수정 api 연동
  src/app/mypage/page.tsx
  src/axios/mypage/api.ts
  src/components/allReview/ReviewCard.tsx
  src/components/allReview/ReviewEditDropdown.tsx
  src/components/gathering/GatheringModal.tsx
  src/components/gatheringDetail/GatheringCreaterProfileGatheringList.tsx
  src/components/mypage/deleteModal.tsx
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myReviewNotWriteDetail.tsx
  src/components/mypage/myReviewCard.tsx
  src/components/mypage/myReviewModal.tsx
  src/components/mypage/myReviewNotWrite.tsx
  src/components/mypage/myReviewWrite.tsx
  src/hooks/useLoadingStateProps.ts
  src/hooks/useReviews.ts
  src/hooks/useUserGatherings.ts
  src/hooks/userUserGatherings.ts
  src/types/mypage.types.ts
Labels: Feat, Fix

#118 FESI1-90: 홈페이지 캐러셀 및 방탈출 테마 추천 페이지 추가
  package-lock.json
  package.json
  public/images/thumbnail.png
  src/app/layout.tsx
  src/app/page.tsx
  src/app/recommend/page.tsx
  src/components/home/Links.tsx
  src/components/home/NearDeadlines.tsx
  src/components/home/NearFullCapacities.tsx
  src/components/home/UI/ArrowButton.tsx
  src/components/home/UI/Carousel.tsx
  src/components/home/UI/GatheringSlot.tsx
  src/components/home/UI/LinkCard.tsx
  src/constants/questionList.ts
Labels: Feat

#119 FESI1-43: 찜한 모임 500에러 수정 및 로딩스피너 수정
  public/loading.svg
  public/spinner.svg
  src/app/likes/page.tsx
  src/axios/likes/apis.ts
  src/components/@shared/Spinner.tsx
  src/components/allReview/AllReviewList.tsx
  src/components/allReview/RatingSection.tsx
Labels: Refactor

#120 FESI1-93: 모임 생성 날짜 오류 및 캘린더 날짜 형식 변환 오류 개선
  package-lock.json
  package.json
  src/components/@shared/calendar/CustomCalendar.tsx
  src/components/@shared/dropdown/DateDropdown.tsx
  src/components/gathering/GatheringModal.tsx
  src/hooks/useToast.ts
  src/utils/dateUtils.ts
Labels: Fix

#121 FESI1-53: Dropdown, Button, 모임 관련 컴포넌트 애니메이션
  src/app/gathering/page.tsx
  src/components/@shared/GenreFilter.tsx
  src/components/@shared/animation/ButtonMotion.tsx
  src/components/@shared/animation/CardMotion.tsx
  src/components/@shared/animation/FadeInMotion.tsx
  src/components/@shared/animation/SlideDownMotion.tsx
  src/components/@shared/animation/SlideTextMotion.tsx
  src/components/@shared/animation/SlotMotion.tsx
  src/components/@shared/animation/TextFadeInMotion.tsx
  src/components/@shared/button/Button.tsx
  src/components/@shared/button/LinkButton.tsx
  src/components/@shared/calendar/DateTimeCalendar.tsx
  src/components/@shared/dropdown/Dropdown.tsx
  src/components/@shared/dropdown/SortDropdown.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/UI/AddGatheringButton.tsx
  src/components/home/UI/GatheringSlot.tsx
  src/styles/globals.css
Labels: Design

#126 FESI1-94 [Feat] : 모임상세 참여하기버튼기능구현 및 기타 디자인 등
  src/app/gathering/[id]/page.tsx
  src/components/gatheringDetail/GatheringDetailSection.tsx
  src/components/gatheringDetail/GatheringMainSection.tsx
Labels: Feat, help wanted

#127 FESI1-95 [Feat] : 94에서 빠진부분 추가
  src/axios/gather/apis.ts
  src/components/gatheringDetail/JoinBoxSection.tsx
Labels: Fix

#129 FESI1-73: 메타 태그 형식 변경
  src/app/layout.tsx
Labels: Fix

#132 FESI1-97: 로그아웃시 토큰 삭제 재구현
  src/axios/auth.ts
  src/axios/interceptors.ts
  src/components/login/LoginForm.tsx
  src/hooks/useAuthNavigation.ts
Labels: Fix

#130 FESI1-90: 방탈출 테마 추천 페이지 추가 디자인 적용
  public/images/recommend_result.png
  public/images/theme_default_xl.png
  src/app/recommend/page.tsx
  src/components/@shared/ProgressPuzzleBar.tsx
  src/components/@shared/animation/FadeInListMotion.tsx
  src/components/@shared/animation/SlideUpMotion.tsx
  src/components/@shared/animation/TextFadeInMotion.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/UI/LevelBadge.tsx
  src/components/recommend/Survey.tsx
  src/components/recommend/SurveyIntro.tsx
  src/components/recommend/SurveyResult.tsx
Labels: Design

#131 FESI1-39: 장르 목록에서 스와이프가 불가능하던 문제
  src/components/@shared/GenreFilter.tsx
  src/styles/globals.css
Labels: Fix

#133 Design: 모임등록 캘린더 AM/PM 위치 변경
  src/components/@shared/calendar/DateTimeCalendar.tsx
  src/components/@shared/calendar/ScrollTimePicker.tsx
Labels: Design

#134 FESI1-70: 마이페이지 api 연동 완성, QA 수정
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/components/@shared/Header.tsx
  src/components/gathering/GatheringModal.tsx
  src/components/mypage/deleteModal.tsx
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/mypage/myGatheringCard.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myReviewNotWriteDetail.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/mypage/myReviewCard.tsx
  src/components/mypage/myReviewModal.tsx
  src/components/mypage/myReviewNotWrite.tsx
  src/components/mypage/myReviewWrite.tsx
  src/types/mypage.types.ts
Labels: Feat, Fix, Design

#136 REFACTOR: 모든 리뷰 페이지 QA QC 반영
  src/components/allReview/ReviewCard.tsx
Labels: Refactor

#137 FESI1-100: 모임 생성 및 수정 페이지 추가 & 스크롤바 디자인 보완
  public/images/puzzle_footer.png
  src/app/gathering/create/page.tsx
  src/app/gathering/page.tsx
  src/app/layout.tsx
  src/app/mypage/[id]/page.tsx
  src/app/test/page.tsx
  src/components/@shared/GenreFilter.tsx
  src/components/@shared/HeaderTitle.tsx
  src/components/@shared/button/LinkButton.tsx
  src/components/@shared/form/Formfield.tsx
  src/components/@shared/form/LoginInput.tsx
  src/components/@shared/input/DateInput.tsx
  src/components/@shared/input/Input.tsx
  src/components/@shared/input/TextArea.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/UI/AddGatheringButton.tsx
  src/components/gathering/selector/ThemeSelector.tsx
  src/components/gatheringEdit/CapacitySelector.tsx
  src/components/gatheringEdit/GatheringFilters.tsx
  src/components/gatheringEdit/GatheringForm.tsx
  src/components/gatheringEdit/LocationSelector.tsx
  src/components/gatheringEdit/ThemeSelector.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/constants/initialValues.ts
  src/hooks/useAuthNavigation.ts
  src/styles/globals.css
  src/styles/scrollbar.css
  src/types/gathering.types.ts
  src/utils/searchUtils.ts
Labels: Feat, Remove, Design

#139 FESI1-70 : header 및 myGatheringCard 반응형 레이아웃 조정
  src/components/@shared/Header.tsx
  src/components/mypage/myGatheringCard.tsx
Labels: Fix

#140 FESI1-90: 테마 추천 페이지 API 연동
  public/images/recommend_empty.png
  src/app/recommend/page.tsx
  src/axios/config/path.ts
  src/axios/theme/apis.ts
  src/components/@shared/animation/CardMotion.tsx
  src/components/@shared/animation/FadeInMotion.tsx
  src/components/@shared/animation/SlideUpMotion.tsx
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/recommend/RecommendCard.tsx
  src/components/recommend/Survey.tsx
  src/components/recommend/SurveyResult.tsx
  src/constants/questionList.ts
  src/types/gathering.types.ts
  src/types/theme.types.ts
Labels: Feat, Design

#142 Fesi1 102 Hot Fix 입니다
  public/icons/share.svg
  src/components/@shared/form/LoginInput.tsx
  src/components/gatheringDetail/GatheringReviewSection.tsx
  src/components/gatheringDetail/JoinBoxSection.tsx
  src/types/gathering.types.ts
  src/types/review.types.ts
Labels: Fix

#143 FESI1-90: 모임 조회 정렬 오류 및 마감 뱃지 수정
  public/icons/arrow_purple.svg
  public/images/banner_default_pc.png
  public/images/banner_recommend.png
  public/images/banner_recommend_pc.png
  src/app/page.tsx
  src/axios/gather/apis.ts
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/UI/PuzzleButton.tsx
  src/components/gatheringEdit/GatheringFilters.tsx
  src/components/gatheringEdit/GatheringForm.tsx
  src/components/gatheringEdit/selector/CapacitySelector.tsx
  src/components/gatheringEdit/selector/LocationSelector.tsx
  src/components/gatheringEdit/selector/ThemeSelector.tsx
  src/components/home/NearRecent.tsx
  src/components/home/UI/Carousel.tsx
  src/components/home/UI/GatheringSlot.tsx
  src/components/recommend/Survey.tsx
  src/components/recommend/SurveyResult.tsx
  src/components/recommend/UI/RecommendCard.tsx
Labels: Fix

#144 FESI1-103 [Feat] : 좋아요, 공유하기 구현, 참여하기버튼 수정
  src/components/gatheringDetail/GatheringMainSection.tsx
  src/components/gatheringDetail/GatheringReviewSection.tsx
  src/components/gatheringDetail/JoinBoxSection.tsx
Labels: Feat, Fix

#146 FESI1-63 : 마이페이지 페이지네이션 구현, search 레이아웃 수정, 모임 수정 props 넘겨주기
  public/icons/ic_arrow_right.svg
  src/app/mypage/[id]/page.tsx
  src/app/mypage/page.tsx
  src/app/search/[keyword]/page.tsx
  src/components/@shared/Pagination.tsx
  src/components/gatheringEdit/GatheringForm.tsx
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myReviewCard.tsx
  src/components/mypage/myReviewNotWrite.tsx
  src/components/mypage/myReviewWrite.tsx
  src/hooks/usePagination.ts
  src/types/mypage.types.ts
Labels: Feat, Fix, Design

#147 FESI1-105: 각 페이지 디자인 통일 작업
  src/app/gathering/[id]/page.tsx
  src/app/recommend/page.tsx
  src/components/@shared/Header.tsx
  src/components/@shared/HeaderNavbar.tsx
  src/components/@shared/Modal.tsx
  src/components/@shared/PageContainer.tsx
  src/components/@shared/Toast.tsx
  src/components/@shared/animation/CardMotion.tsx
  src/components/@shared/animation/SlotMotion.tsx
  src/components/@shared/button/IconButton.tsx
  src/components/allReview/ReviewCard.tsx
  src/components/gatheringEdit/GatheringForm.tsx
  src/components/mypage/myGatheringCard/myReviewNotWriteDetail.tsx
  src/components/recommend/Survey.tsx
  src/components/recommend/SurveyResult.tsx
  src/styles/globals.css
Labels: Design

#149 FESI1-73: 페이지 title 형식 통일 & 구글 메타 태그 설정
  src/app/allreview/page.tsx
  src/app/gathering/[id]/page.tsx
  src/app/gathering/create/page.tsx
  src/app/gathering/page.tsx
  src/app/layout.tsx
  src/app/likes/page.tsx
  src/app/mypage/[id]/page.tsx
  src/app/mypage/page.tsx
  src/app/recommend/page.tsx
  src/app/search/[keyword]/page.tsx
  src/components/@shared/HeaderTitle.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
Labels: Docs

#148 FESI1-106: QA fix complete
  public/icons/chevron_vector.svg
  src/app/gathering/[id]/page.tsx
  src/components/gatheringDetail/GatheringDetailSection.tsx
  src/components/gatheringDetail/GatheringMainSection.tsx
  src/components/gatheringDetail/GatheringReviewSection.tsx
  src/components/gatheringDetail/JoinBoxSection.tsx
  src/components/login/LoginForm.tsx
  src/data/mockGatheringDetail.ts
  src/types/gathering.types.ts
Labels: Fix, Design

#150 FESI1-70: header 및 페이지네이션 레이아웃 조정 & 모임 수정 컴포넌트 message props 추가
  src/app/mypage/[id]/page.tsx
  src/components/@shared/Header.tsx
  src/components/@shared/Pagination.tsx
  src/components/gatheringEdit/GatheringForm.tsx
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/mypage/myReviewNotWrite.tsx
  src/components/mypage/myReviewWrite.tsx
Labels: Fix

#151 FESI1-105: 105 브랜치에서 적용되지 않은 부분 재 PR
  src/app/search/[keyword]/page.tsx
  src/components/@shared/Header.tsx
  src/components/@shared/Toast.tsx
Labels: Design

#155 Update README.md
  README.md
Labels: Docs
