Repository Codeit-FESI-06-Team2/MoYeoBang, pull requests merged in 2025-01, with the labels that each got.

#2 vercel 배포를 위한 코드 수정
  .eslintrc.js
  .github/pull_request_template.md
  package.json
  src/app/allreview/page.tsx
  src/app/gathering/[id]/page.tsx
  src/app/layout.tsx
  src/app/likes/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/axios/api.ts
  src/components/@shared/(삭제) 깃허브 인식용
  src/components/allReview/(삭제) 깃허브 인식용
  src/components/gathering/(삭제) 깃허브 인식용
  src/components/gatheringDetail/(삭제) 깃허브 인식용
  src/components/likes/(삭제) 깃허브 인식용
  src/components/login/(삭제) 깃허브 인식용
  src/components/mypage/(삭제) 깃허브 인식용
  src/components/signup/(삭제) 깃허브 인식용
  src/hooks/useUser.ts
  src/lib/(삭제) 깃허브 인식용
  src/providers/providers.tsx
  src/store/atoms/userAtoms.ts
  src/store/index.ts
  src/store/selectors/userSelectors.ts
  src/styles/globals.css
  src/types/index.ts
Labels: Fix

#3 package.json 오류로 인한 긴급 수정
  package.json
Labels: Fix

#4 FESI1-15: 공통 컴포넌트 버튼 제작
  next.config.ts
  package-lock.json
  package.json
  src/app/test/page.tsx
  src/components/@shared/(삭제) 깃허브 인식용
  src/components/@shared/Button.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: Feat, Chore

#7 FESI1-14: 공용 컴포넌트 gnb 구현
  package-lock.json
  package.json
  public/Vector.png
  public/delete.svg
  src/app/layout.tsx
  src/components/@shared/Header.tsx
  src/components/@shared/HeaderSlidebar.tsx
  tsconfig.json
Labels: Feat

#8 FESI1-16: 공통 Input 컴포넌트 및 TextArea 컴포넌트 제작 & Button 컴포넌트 수정
  .eslintrc.js
  package-lock.json
  package.json
  src/app/test/page.tsx
  src/components/@shared/Button.tsx
  src/components/@shared/Input.tsx
  src/components/@shared/TextArea.tsx
  tsconfig.json
Labels: Feat, Chore

#6 FESI1-26: 공용 컴포넌트 모달 구현
  .vscode/settings.json
  package-lock.json
  src/app/test/page.tsx
  src/components/@shared/Modal.tsx
  tsconfig.json
Labels: Feat

#10 Chore : next.js 패키지 다운 및 eslint 오류 해결
  .eslintignore
  .eslintrc.js
  .gitignore
  next.config.js
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/test/page.tsx
  src/axios/api.ts
  src/components/@shared/Header.tsx
  src/components/@shared/Modal.tsx
  src/hooks/useUser.ts
  src/providers/providers.tsx
  src/store/atoms/userAtoms.ts
  src/store/index.ts
  src/store/selectors/userSelectors.ts
  tsconfig.json
Labels: Chore

#12 Fix: next.js 패키지 다운 , gnb 코드 리팩토링 및 eslint 오류 해결
  package-lock.json
  src/components/@shared/Header.tsx
Labels: Refactor, Chore, Fix

#11 Chore: 패키지 버전 통일 & 폰트 적용
  .gitignore
  next.config.mjs
  package.json
  postcss.config.mjs
  src/app/fonts/PretendardVariable.woff2
  src/app/test/page.tsx
  src/components/@shared/Button.tsx
  src/components/@shared/Input.tsx
  src/styles/globals.css
Labels: Chore, Fix

#14 FESI1-26: 공용 컴포넌트 모달 배경 스타일 변경
  src/components/@shared/Modal.tsx
Labels: Style

#15 FESI-36 : 공용 컴포넌트 Rating, RatingInput 구현
  src/components/@shared/Rating.tsx
  src/components/@shared/RatingInput.tsx
Labels: Feat

#16 FESI1-19: 모임 찾기 페이지, 레이아웃 및 반응형 디자인 적용
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/fonts/PretendardVariable.woff2
  public/icons/alarm.svg
  public/icons/creator.svg
  public/icons/heart_empty.svg
  public/icons/heart_full.svg
  public/icons/level_low.svg
  public/icons/user.svg
  public/icons/visibility_focus.svg
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/@shared/ProgressBar.tsx
  src/components/gathering/(삭제) 깃허브 인식용
  src/components/gathering/AlarmBadge.tsx
  src/components/gathering/GatheringBadge.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringFilters.tsx
  src/components/gathering/GenreFilters.tsx
  src/components/gathering/HeartButton.tsx
  src/data/mockGatherings.ts
  src/data/themeList.ts
  src/styles/globals.css
  src/types/gathering.types.ts
  src/types/index.ts
  src/utils/dateUtils.ts
  src/utils/numberUtils.ts
  tailwind.config.ts
Labels: Chore, Design

#13 FESI1-34: 지역 선택 드랍다운 공통 컴포넌트
  public/chevron-down.svg
  src/app/test/page.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
Labels: Feat

#20 FESI1-20: 모임 찾기 페이지, 디자인 테스트를 위한 dev 브랜치 병합
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  public/fonts/PretendardVariable.woff2
  public/icons/alarm.svg
  public/icons/creator.svg
  public/icons/heart_empty.svg
  public/icons/heart_full.svg
  public/icons/level_low.svg
  public/icons/user.svg
  public/icons/visibility_focus.svg
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/@shared/ProgressBar.tsx
  src/components/gathering/(삭제) 깃허브 인식용
  src/components/gathering/AlarmBadge.tsx
  src/components/gathering/GatheringBadge.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringFilters.tsx
  src/components/gathering/GenreFilters.tsx
  src/components/gathering/HeartButton.tsx
  src/data/mockGatherings.ts
  src/data/themeList.ts
  src/styles/globals.css
  src/types/gathering.types.ts
  src/types/index.ts
  src/utils/dateUtils.ts
  src/utils/numberUtils.ts
  tailwind.config.ts
Labels: Test

#21 FESI1-42:반응형 gnb로 레이아웃 변경/마이페이지 레이아웃 설정, 마이페이지 정보 수정 모달 dev 브랜치로 병합
  public/Vector.png
  public/default_mypage.png
  public/edit.png
  public/hamburger.png
  public/profile_image_default.png
  public/refresh.png
  public/search.png
  public/search_delete.png
  src/app/mypage/myGathering.tsx
  src/app/mypage/myLike.tsx
  src/app/mypage/myReview.tsx
  src/app/mypage/page.tsx
  src/components/@shared/Header.tsx
  tailwind.config.ts
Labels: Refactor

#23 FIX : 2차 배포 테스트 allReview 파트 lint 에러 해결
  src/components/allReview/RatingSection.tsx
  src/components/allReview/ReviewGenreFilter.tsx
Labels: Fix

#25 FESI1-27 : 공용 컴포넌트 Calendar 구현
  package-lock.json
  package.json
  src/app/test/page.tsx
  src/components/@shared/Button.tsx
  src/components/@shared/CustomCalendar.tsx
  src/styles/globals.css
  src/utils/dateUtils.ts
Labels: Feat

#18 Fesi1-43: loading spinner
  public/spinner.svg
  src/app/test/page.tsx
  src/components/@shared/Dropdown.tsx
  src/components/@shared/Spinner.tsx
  src/components/@shared/Spinner/index.tsx
Labels: Feat

#24 mypage, header lint 오류 수정, modal을 컴포넌트로 변경, mypage 하위 컴포넌트 폴더 위치 변경, user dto 설정, mock data 사용
  src/app/mypage/myGathering.tsx
  src/app/mypage/myLike.tsx
  src/app/mypage/myReview.tsx
  src/app/mypage/page.tsx
  src/components/@shared/Header.tsx
  src/components/mypage/(삭제) 깃허브 인식용
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/mypage/myReview.tsx
  src/data/mockUser.ts
  src/types/mypage.types.ts
Labels: Refactor, Fix

#27 Test : github actions 테스트를 위한 PR
  .github/workflows/lint.yml
Labels: Test

#28 FIX : vercel 2차 배포 오류 수정 (1)
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/components/gathering/GatheringCard.tsx
  src/types/mypage.types.ts
Labels: Fix

#30 FIX : modal 이미지 오류 및 레이팅 그래프 오류 수정
  .github/workflows/lint.yml
  src/components/@shared/Modal.tsx
  src/components/allReview/RatingSection.tsx
  tailwind.config.ts
Labels: Fix

#31 FESI1-32: 모든 리뷰 페이지 1차 디자인 테스트 피드백 반영
  src/app/allreview/page.tsx
  src/components/allReview/ReviewCard.tsx
Labels: Design

#32 FESI1-37: 모임 생성 모달 제작
  package-lock.json
  package.json
  public/icons/minus.svg
  public/icons/plus.svg
  src/app/page.tsx
  src/components/@shared/Button.tsx
  src/components/gathering/CapacitySelector.tsx
  src/components/gathering/CreateGatheringBtn.tsx
  src/components/gathering/CreateGatheringModal.tsx
  src/components/gathering/LocationSelector.tsx
  src/components/gathering/ThemeSelector.tsx
  src/constants/initialValues.ts
  src/constants/themeList.ts
  src/hooks/useCustomForm.ts
  src/hooks/useModal.ts
  src/types/gathering.types.ts
  tailwind.config.ts
Labels: Feat, Chore

#35 FESI1-32: 모든 리뷰 페이지 필터 구현
  src/app/allreview/page.tsx
  src/components/@shared/CustomCalendar.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/allReview/LocationDropdown.tsx
  src/components/allReview/ReviewFilters.tsx
  src/components/allReview/ReviewSection.tsx
  src/data/mockReviews.ts
Labels: Feat

#36 FESI1-38: 모임 찜 등록 및 취소 기능
  src/app/gathering/[id]/page.tsx
  src/app/page.tsx
  src/components/gathering/GatheringBadge.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/HeartButton.tsx
  src/types/gathering.types.ts
Labels: Feat

#42 FESI1-27: 공용 컴포넌트 캘린더 리팩토링
  public/HeartFull.svg
  public/HeartLine.svg
  public/puzzle_empty.png
  src/app/allreview/page.tsx
  src/app/layout.tsx
  src/components/@shared/CustomCalendar.tsx
  src/components/@shared/EmptyElement.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/allReview/LocationDropdown.tsx
  src/components/allReview/RatingSection.tsx
  src/components/allReview/ReviewCard.tsx
  src/components/allReview/ReviewFilters.tsx
  src/components/allReview/ReviewSection.tsx
  src/components/allReview/SortDropdown.tsx
  src/components/gathering/GatheringCard.tsx
  src/hooks/useCalendar.ts
  src/styles/globals.css
  src/utils/dateUtils.ts
  tailwind.config.ts
Labels: Refactor

#41 FESI1-15: 공통 버튼 컴포넌트 수정 & 아이콘 버튼 컴포넌트 추가
  public/icons/pencil.svg
  src/app/test/page.tsx
  src/components/@shared/Button.tsx
  src/components/@shared/IconButton.tsx
  tailwind.config.ts
Labels: Feat, Design

#40 FESI1-49: 404 페이지
  public/puzzle_empty.png
  src/app/not-found.tsx
  src/app/test/page.tsx
Labels: Feat

#48 FESI1-37: 모임 생성 모달 로직 및 디자인 보완
  public/icons/minus.svg
  public/icons/plus.svg
  src/components/gathering/CapacitySelector.tsx
  src/components/gathering/CreateGatheringBtn.tsx
  src/components/gathering/GatheringModal.tsx
  src/components/gathering/LocationSelector.tsx
  src/components/gathering/ThemeSelector.tsx
  src/utils/dateUtils.ts
Labels: Design

#47 FESI1-55: 모든 리뷰 리팩토링 및 찜한 모임 구현
  src/app/allreview/page.tsx
  src/app/likes/page.tsx
  src/components/@shared/GenreFilter.tsx
  src/components/@shared/HeaderTitle.tsx
  src/components/@shared/PageContainer.tsx
  src/components/allReview/AllReviewList.tsx
  src/components/allReview/ReviewGenreFilter.tsx
  src/components/allReview/ReviewSection.tsx
  src/components/gathering/GatheringFilters.tsx
  src/components/gathering/GatheringList.tsx
  src/components/likes/(삭제) 깃허브 인식용
  src/components/likes/LikesGatheringList.tsx
  src/types/gathering.types.ts
  src/types/review.types.ts
Labels: Feat, Refactor

#50 FESI1-41: 모임 목록 정렬 기능 & 아이콘 변경
  public/icons/graph_high.svg
  public/icons/graph_low.svg
  public/icons/graph_middle.svg
  public/icons/puzzle_full.svg
  public/icons/puzzle_line.svg
  public/icons/sort.svg
  public/refresh.png
  src/components/@shared/SortDropdown.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/allReview/ReviewFilters.tsx
  src/components/allReview/SortDropdown.tsx
  src/components/gathering/GatheringBadge.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/LevelDropdown.tsx
  src/components/gathering/PuzzleButton.tsx
  src/constants/sortList.ts
  src/utils/dateUtils.ts
  src/utils/sortUtils.ts
Labels: Feat, Design

#53 FESI1-19: 마이페이지 모달 기능 구현, 퍼즐 배경 반응형 디자인
  public/myprofile_bg/L/1.png
  public/myprofile_bg/L/2.png
  public/myprofile_bg/L/3.png
  public/myprofile_bg/L/4.png
  public/myprofile_bg/L/5.png
  public/myprofile_bg/L/6.png
  public/myprofile_bg/l/1.svg
  public/myprofile_bg/l/2.svg
  public/myprofile_bg/l/3.svg
  public/myprofile_bg/l/4.svg
  public/myprofile_bg/l/5.svg
  public/myprofile_bg/l/6.svg
  public/myprofile_bg/s/1.svg
  public/myprofile_bg/s/2.svg
  public/myprofile_bg/s/3.svg
  public/myprofile_bg/s/4.svg
  public/myprofile_bg/s/5.svg
  public/myprofile_bg/s/6.svg
  src/app/mypage/page.tsx
  src/components/@shared/Header.tsx
  src/components/gathering/GatheringList.tsx
  src/components/mypage/deleteModal.tsx
  src/components/mypage/myCreateGathering.tsx
  src/components/mypage/myGathering.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/mypage/myReviewCard.tsx
  src/components/mypage/myReviewModal.tsx
  src/components/mypage/myReviewNotWrite.tsx
  src/components/mypage/myReviewWrite.tsx
Labels: Feat, Design

#54 FESI1-57: 홈 페이지 구현
  public/icons/arrow_line_black.svg
  public/icons/arrow_line_white.svg
  public/images/puzzle_banner.png
  public/images/puzzle_deadline_mb.png
  public/images/puzzle_deadline_pc.png
  public/images/puzzle_deadline_tb.png
  public/images/puzzle_likes.png
  public/images/puzzle_review.png
  src/app/gathering/page.tsx
  src/app/page.tsx
  src/components/@shared/Header.tsx
  src/components/@shared/LinkButton.tsx
  src/components/@shared/Pagination.tsx
  src/components/gathering/GatheringList.tsx
  src/components/home/GatheringSlot.tsx
  src/components/home/LinkCard.tsx
  src/components/home/Links.tsx
  src/components/home/NearDeadlines.tsx
  src/components/home/NearFullCapacities.tsx
  src/hooks/usePagination.ts
  src/types/gathering.types.ts
Labels: Feat, Design

#55 FESI1-64: 찜한 모임 로컬 스토리지 구현 및 각 페이지 디자인 변경
  src/app/likes/page.tsx
  src/components/@shared/DateTimeCalendar.tsx
  src/components/@shared/PageContainer.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
  src/components/allReview/DateDropdown.tsx
  src/styles/customCalendar.css
  src/styles/dateTimeCalendar.css
Labels: Feat, Design

#56 FESI1-15: 공통 버튼 varient 및 shape 속성 추가
  src/app/test/page.tsx
  src/components/@shared/Button.tsx
Labels: Design

#57 FESI1-65: 홈 페이지 디자인 수정
  src/app/gathering/page.tsx
  src/app/page.tsx
  src/components/@shared/HeaderTitle.tsx
  src/components/gathering/AlarmBadge.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/PuzzleButton.tsx
  src/components/home/GatheringSlot.tsx
  src/components/home/NearDeadlines.tsx
Labels: Design

#58 FESI1-62 모임상세- 모임 주최자 프로필 모달 반응형 레이아웃 구현
  public/icons/right.svg
  src/app/gathering/[id]/page.tsx
  src/app/mypage/page.tsx
  src/components/gatheringDetail/(삭제) 깃허브 인식용
  src/components/gatheringDetail/GatheringCreaterProfileGatheringList.tsx
  src/components/gatheringDetail/GatheringCreaterProfileModal.tsx
  src/data/mockGatheringCreater.ts
  src/styles/globals.css
  src/types/gathering.types.ts
Labels: Feat, Design

#60 FESI1-67: 기존 드롭다운 개선 & 정렬 드롭다운 분리
  src/components/@shared/SortDropdown.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/allReview/LocationDropdown.tsx
  src/components/gathering/LevelDropdown.tsx
  src/constants/themeList.ts
Labels: Feat

#62 로그인 및 회원가입 페이지 퍼블리싱
  .prettierrc
  package-lock.json
  public/myprofile_bg/L/1.png
  public/myprofile_bg/L/2.png
  public/myprofile_bg/L/3.png
  public/myprofile_bg/L/4.png
  public/myprofile_bg/L/5.png
  public/myprofile_bg/L/6.png
  public/signup_puzzle.svg
  public/signup_small.svg
  public/signup_small_screen.svg
  src/app/login/page.tsx
  src/app/mypage/myGathering.tsx
  src/app/mypage/myLike.tsx
  src/app/mypage/myReview.tsx
  src/app/signup/page.tsx
  src/app/test/page.tsx
  src/components/@shared/GenreFilter.tsx
  src/components/@shared/Spinner.tsx
  src/components/@shared/Spinner/index.tsx
  src/components/@shared/ToggleInput.tsx
  src/components/@shared/form/Formfield.tsx
  src/components/gathering/PuzzleButton.tsx
  src/components/login/(삭제) 깃허브 인식용
  src/components/login/LoginForm.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/signup/(삭제) 깃허브 인식용
  src/components/signup/SignUpForm.tsx
Labels: Feat, Design

#63 FESI1-70: 불필요한 파일 제거
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myReviewNotWriteDetail.tsx
Labels: Remove

#64 3차 배포 오류 수정
  src/app/likes/page.tsx
Labels: Fix

#65 FESI1-70: hotfix
  src/app/mypage/myGathering.tsx
  src/app/mypage/myLike.tsx
  src/app/mypage/myReview.tsx
Labels: Fix

#66 FESI1-70: 파일 되돌리기
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myReviewNotWriteDetail.tsx
Labels: Fix

#67 FESI-14: 모바일 nav 화면 구현 및 QA 제안 수정
  public/hamburger.png
  public/icons/ic_delete.svg
  public/icons/mobile_nav.svg
  public/icons/search.svg
  src/components/@shared/Header.tsx
  src/components/@shared/HeaderNavbar.tsx
  src/components/@shared/HeaderSlidebar.tsx
Labels: Feat

#68 FESI1-71: QA Fix 및 Dev Build Test 추가
  .github/workflows/build-test.yml
  .github/workflows/lint.yml
  .github/workflows/sync-main.yml
  src/components/@shared/EmptyElement.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/allReview/ReviewCard.tsx
  src/components/allReview/ReviewEditDropdown.tsx
  src/data/mockReviewRatings.ts
Labels: Feat, Design

#69 FESI1-20: 스크롤바 및 모임 찾기 페이지 디자인 수정
  src/components/@shared/GenreFilter.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/PuzzleButton.tsx
  src/components/gathering/ThemeSelector.tsx
  src/components/home/GatheringSlot.tsx
  src/components/home/LinkCard.tsx
  src/styles/globals.css
Labels: Design

#70 마이페이지, GNB QA 수정
  public/Logo.svg
  public/Logo_Large.png
  public/default_mypage.png
  public/edit.png
  public/edit_icon.png
  public/icons/btn_edit.svg
  public/icons/profile_image_default.svg
  src/app/mypage/page.tsx
  src/components/@shared/Header.tsx
  src/components/mypage/deleteModal.tsx
  src/components/mypage/myGatheringCard.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myReviewNotWriteDetail.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/mypage/myReviewCard.tsx
  src/components/mypage/myReviewModal.tsx
Labels: Design

#71 FESI1-46: 회원가입 및 로그인 유효성 검사
  package-lock.json
  src/axios/api.ts
  src/axios/auth.ts
  src/axios/axios.ts
  src/components/@shared/form/Formfield.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SignUpForm.tsx
  src/styles/globals.css
Labels: Feat, help wanted

#72 FESI1-37: 모임 생성 모달 시간 캘린더 연동
  public/icons/calendar.svg
  public/images/puzzle_banner.png
  src/app/gathering/page.tsx
  src/components/@shared/DateInput.tsx
  src/components/@shared/DateTimeCalendar.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/GatheringModal.tsx
  src/components/gathering/UI/AddGatheringButton.tsx
  src/components/gathering/UI/AlarmBadge.tsx
  src/components/gathering/UI/GatheringBadge.tsx
  src/components/gathering/selector/CapacitySelector.tsx
  src/components/gathering/selector/GatheringFilters.tsx
  src/components/gathering/selector/LevelDropdown.tsx
  src/components/gathering/selector/LocationSelector.tsx
  src/components/gathering/selector/ThemeSelector.tsx
  src/components/home/GatheringSlot.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myGatheringCard/myGatheringDetail.tsx
  src/constants/themeList.ts
  src/data/mockGatherings.ts
  src/types/gathering.types.ts
Labels: Feat

#74 FEAT: 상세페이지 DTO와 mockdata 추가
  src/app/gathering/[id]/page.tsx
  src/axios/auth.ts
  src/data/mockGatheringDetail.ts
  src/types/gathering.types.ts
Labels: Feat

#77 Fesi1 75 login : 회원가입,로그인 로직구현 , API 서버 연동
  src/components/@shared/form/Formfield.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SignUpForm.tsx
Labels: Feat, Fix

#78 Fix : 로그인 오류 1차 해결
  src/components/@shared/form/Formfield.tsx
  src/components/@shared/form/LoginInput.tsx
  src/components/login/LoginForm.tsx
Labels: Fix

#79 FESI1-70: 마이페이지에서 사용하는 모달 미기능 alert 창 추가, GNB 클릭 이벤트 추가
  src/components/@shared/Header.tsx
  src/components/mypage/deleteModal.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/mypage/myReviewCard.tsx
  src/components/mypage/myReviewModal.tsx
Labels: Feat, Fix

#82 FESI1-67: 드롭다운 모바일 디자인 변경
  src/components/@shared/SortDropdown.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/gathering/GatheringCard.tsx
  src/components/gathering/GatheringList.tsx
  src/data/mockGatheringCreater.ts
  src/data/mockGatherings.ts
  src/utils/dateUtils.ts
Labels: Design

#84 FESI-14 : 로그인, 로그아웃 시 header 우측 버튼 변경
  src/components/@shared/Header.tsx
  src/components/login/LoginForm.tsx
Labels: Feat, Fix

#85 FESI1-76: 공통 Toast 컴포넌트 구현
  public/icons/checkbox.svg
  public/icons/warning.svg
  src/components/@shared/Toast.tsx
  src/components/gathering/GatheringModal.tsx
  src/hooks/useToast.ts
  src/styles/globals.css
Labels: Feat

#87 Refector : 미구현창 공용 컴포넌트 Toast로 통일
  src/components/@shared/Header.tsx
  src/components/login/LoginForm.tsx
  src/components/mypage/deleteModal.tsx
  src/components/mypage/myProfileEditModal.tsx
  src/components/mypage/myReviewModal.tsx
  src/components/signup/SignUpForm.tsx
Labels: Refactor

#86 FESI1-62 [Feat] : 모임상세 레이아웃 구현
  public/icons/location.svg
  src/app/gathering/[id]/page.tsx
  src/components/gatheringDetail/GatheringDetailSection.tsx
  src/components/gatheringDetail/GatheringMainSection.tsx
  src/components/gatheringDetail/GatheringReviewSection.tsx
  src/components/gatheringDetail/JoinBoxSection.tsx
  src/components/gatheringDetail/ProfileSection.tsx
Labels: Design

#88 FESI1-37: 시간 캘린더 모달 디자인 & 날짜 필터 오류 개선
  src/components/allReview/AllReviewList.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/gathering/GatheringModal.tsx
  src/utils/filterUtils.ts
Labels: Fix, Design

#89 hover 이슈 해결
  src/components/@shared/Header.tsx
  src/components/login/LoginForm.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myReviewCard.tsx
Labels: Fix

#92 FESI-70 [Fix]: ul dropdown state를 hook으로 관리
  src/components/@shared/Header.tsx
  src/components/mypage/myGatheringCard/myCreateGatheringDetail.tsx
  src/components/mypage/myReviewCard.tsx
  src/hooks/useDropdown.ts
Labels: Refactor, Fix

#93 FESI1-77: useQuery를 활용한 찜한 모임 api 호출 로직 구현
  src/app/likes/page.tsx
  src/axios/auth.ts
  src/axios/axiosInstance.ts
  src/axios/config/path.ts
  src/axios/likes/apis.ts
  src/components/@shared/EmptyElement.tsx
  src/components/@shared/QueryProvider.tsx
Labels: Feat

#94 FESI1-79: 모든 리뷰 ReactQuery 활용한 API 연동 구현
  next.config.js
  src/app/allreview/page.tsx
  src/app/likes/page.tsx
  src/axios/allReview/apis.ts
  src/components/allReview/AllReviewList.tsx
  src/components/allReview/RatingSection.tsx
  src/data/mockReviewRatings.ts
  src/types/review.types.ts
Labels: Feat

#95 FESI1-40: 모임 찾기 페이지 API 연동
  package-lock.json
  package.json
  src/app/gathering/page.tsx
  src/axios/gather/apis.ts
  src/components/@shared/GenreFilter.tsx
  src/components/@shared/Toast.tsx
  src/components/@shared/calendar/CustomCalendar.tsx
  src/components/@shared/dropdown/SelectLocationDropdown.tsx
  src/components/allReview/DateDropdown.tsx
  src/components/allReview/LocationDropdown.tsx
  src/components/gathering/GatheringList.tsx
  src/components/gathering/GatheringModal.tsx
  src/components/gathering/selector/LevelDropdown.tsx
  src/components/gathering/selector/LocationSelector.tsx
  src/components/likes/LikesGatheringList.tsx
  src/constants/sortList.ts
  src/constants/themeList.ts
  src/hooks/useCustomForm.ts
  src/types/gathering.types.ts
  src/utils/apiCall.ts
  src/utils/dateUtils.ts
Labels: Feat, Fix

#99 FESI1-73: 메타 태그 설정
  public/icons/favicon.svg
  public/images/thumnail.png
  src/app/layout.tsx
Labels: Feat

#98 FESI1-40: 홈 페이지 API 연동
  src/app/page.tsx
  src/components/gathering/GatheringList.tsx
  src/components/home/NearDeadlines.tsx
  src/components/home/NearFullCapacities.tsx
Labels: Feat

#101 FESI1-80 : API 인증 , access token 관련 로직 구현
  package-lock.json
  src/axios/auth.ts
  src/axios/axiosInstance.ts
  src/axios/constants.ts
  src/axios/interceptors.ts
  src/components/login/LoginImages.tsx
  src/utils/logger.ts
Labels: Feat

#102 Fesi1 81 : localstroage 에 authorization 이 담기게 수정
  src/axios/auth.ts
Labels: Fix

#103 FESI1-40: Authorization 오류 개선
  next.config.js
  src/axios/allReview/apis.ts
  src/axios/auth.ts
  src/axios/axiosInstance.ts
  src/axios/likes/apis.ts
  src/axios/mypage/api.ts
  src/components/gathering/GatheringList.tsx
  src/components/gathering/GatheringModal.tsx
  src/components/gathering/UI/AddGatheringButton.tsx
  src/constants/initialValues.ts
  src/hooks/useAuthNavigation.ts
  src/utils/apiCall.ts
  src/utils/dateUtils.ts
  src/utils/filterUtils.ts
  src/utils/searchUtils.ts
Labels: Feat, Fix
